// <auto-generated />
namespace Back_End.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class trucknumber_DIstanceTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trucknumber_DIstanceTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201801041413462_trucknumber_DIstanceTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
